Added a fix to the unverified system
Sachin-dot-py/r-IGCSEBot pull request #53
Opened 2022-10-01 11:34 UTC by vsmart-06

2022-10-01 11:39 UTC, Infiniticity requested changes

2022-10-01 11:39 UTC, Infiniticity commented on app.py
> +        if await hasRole(user, "Stage 1 - Unverified") and reaction.channel.id == 1024872365894672425:
```suggestion
        if await hasRole(user, "Stage 1 - Unverified") and reaction.message.id == 1025236702379389001:
```

2022-10-01 11:41 UTC, Infiniticity approved these changes

2022-10-01 11:57 UTC, Sachin-dot-py requested changes
The option "Not an IGCSE student" in the exam board embed should fully verify the user

2022-10-01 12:17 UTC, vsmart-06 reviewed
Changes made

2022-10-02 03:22 UTC, Sachin-dot-py approved these changes

2022-10-02 03:23 UTC, merged